### ISSUE TITLE
getpass asks for the password but never uses it

### ISSUE THREAD

**Issue by asolino** [the-useless-one/pywerview#1]
If you run the script w/o specifying the password, it will prompt for the password but it will never be used.

Problem lies [here](https://github.com/the-useless-one/pywerview/blob/master/pywerview.py#L271), it should be replaced to:

``` python
    if not args.password and not args.hashes:
        from getpass import getpass
        args.password = getpass('Password:')
```

**Comment by the-useless-one** [comment]
Whoops, thanks for the catch!
