### ISSUE TITLE
PyPi package 

### ISSUE THREAD

**Issue by byt3bl33d3r** [the-useless-one/pywerview#13]
Heya,
More of a question than an issue, was wondering if you'll be publishing this to Pypi? this will allow me to use Pywerview in [CrackMapExec](https://github.com/byt3bl33d3r/CrackMapExec) (sort of a match made in heaven really).

Thanks!

**Comment by the-useless-one** [comment]
Hey there!

I hadn't thought of this, but I guess I could! I'll give it a look (leaving this open for now).

Cheers,

Y

**Comment by byt3bl33d3r** [comment]
Awesome, thanks man! :D

**Comment by the-useless-one** [comment]
Hey @byt3bl33d3r, just to let you know, I'm really considering doing this, but since this PR CoreSecurity/impacket#191, I'm probably gonna do some major changes to the internal API (nothing should change on the CLI tool). So this may take a while, but don't think I'm forgetting this!

Cheers,

Y

**Comment by byt3bl33d3r** [comment]
Awesome thanks! Once you do let me know!

**Comment by the-useless-one** [comment]
Hey man, as you can see, I've finished my internal rewriting. The problem is, now my tool depends on impacket >= 0.9.16-dev, which is not available on PyPi :confused:. Isn't it a problem to deploy my tool? I've never used PyPi before.

Let me know what you think!

**Comment by byt3bl33d3r** [comment]
lol I literally had this problem a couple of months ago (https://github.com/CoreSecurity/impacket/issues/164). Pinging @asolino once again, but he usually releases a new version on Pypi twice a year.

**Comment by byt3bl33d3r** [comment]
Going to dig into the setuptools docs again to find a way around this. There has to be a way of using git repos as packages

**Comment by the-useless-one** [comment]
Alright, (almost) everything is ready for a release on PyPI, I'm just having trouble cause I released to early a v0.1.0 on PyPI, and I can't update it (having proper development and release practice is _hard_!)...

So you'll have to wait for the next feature add/bug fix so that I can change the version tag ;)

Cheers,

Y
