### ISSUE TITLE
Use add_argument's required parameter for those parameters that are required

### ISSUE THREAD

**Issue by asolino** [the-useless-one/pywerview#2]
For example, when trying to use the `invoke-checklocaladminaccess` action, you get:

```
usage: pywerview.py invoke-checklocaladminaccess [-h] [-w DOMAIN] -u USER
                                                 [-p PASSWORD]
                                                 [--hashes LMHASH:NTHASH]
                                                 [--computername TARGET_COMPUTERNAME]
```

but, if you don't specify `computername` parameter the module will fail.. and.. I think you really need to specify it ;).
In the same way as the `USER` parameter, you can define `computername` this way:

```
    invoke_checklocaladminaccess_parser.add_argument('--computername', required=True, dest='target_computername',
            help='Computer to test local admin access on')
```

and will force the script to check that parameter was provided.

I saw this happening on other actions as well.

**Comment by the-useless-one** [comment]
Yep, this problem was also present for other commands (basically, commands targeting domain computers, and not domain controllers). Should be fixed now, thanks!
