### ISSUE TITLE
Any chance of adding kerberos auth?

### ISSUE THREAD

**Issue by rjk11111** [the-useless-one/pywerview#25]
stealing kerberos tickets is a decent way to operate within the user space. Any chance you can utilize impackets kerberos auth?

https://github.com/CoreSecurity/impacket/blob/master/examples/GetUserSPNs.py#L117 
has a decent method of kerberos auth with the dc-ip option for specify the krb host from .

**Comment by the-useless-one** [comment]
Hi @rkornmeyer,

Yes, Kerberos authentication is in my TODO list. I'd say it's a mid-term objective. I'll leave the issue open to remind me that it's a wanted feature. Thanks!

**Comment by ksecurity45** [comment]
Please Add kerberos auth. Highly appreciated.

**Comment by the-useless-one** [comment]
Hi @ksecurity45,

It's a long overdue feature, and we're actually currently implementing it, it should be pushed in the `develop` branch relatively soon. I'll keep this issue open until it's done.

**Comment by the-useless-one** [comment]
Hi @ksecurity45 and @rkornmeyer,

Kerberos authentication is now supported by `pywerview`! Closing.
