### ISSUE TITLE
Return JSON objects

### ISSUE THREAD

**Issue by bmarsh9** [the-useless-one/pywerview#29]
Hi there, love the program. Is there an easy way to return all the results as a JSON object instead of just text with newlines?

**Comment by the-useless-one** [comment]
Hi @bm1391,

Sorry about the delay. As you can see, (and as my colleagues like to remind me, hi guys! :wave:), I don't have much time to take care of this project. Please, feel free make a pull request, if you have time to implement this feature.

Cheers,

Y

**Comment by bmarsh9** [comment]
Thanks! This seemed to do the trick

```
    final = []
    for record in results:
        temp = {}
        for key,value in record.__dict__.items():
            temp[key] = value
        final.append(temp)
    return final
```
