### ISSUE TITLE
Use the same capitalization for actions as PowerView functions

### ISSUE THREAD

**Issue by asolino** [the-useless-one/pywerview#3]
This is not a functional issue, but just an opinion.. and of course it's up to @the-useless-one to decide. I would however, use the same capitalization as PowerView's functions. For example:
1. _invoke-checklocaladminaccess_ to _Invoke-CheckLocalAdminAccess_
2. _get-netgroupmember_ to _Get-NetGroupMember_
and so on.

I would do the same for the specific parameters for each function.

Why?.. Besides looking prettier (personal opinion ;) ), it will help PowerView users to transition easier to this script, and the other way around too!

**Comment by the-useless-one** [comment]
Thanks for the suggestion, I'll think about it!

**Comment by byt3bl33d3r** [comment]
+1 to @asolino's comment. Ideally, I'd like to see things work _with_ and _without_ capitalization. Going to have to dig into the argparse library to see if there's a way of doing this.

**Comment by the-useless-one** [comment]
I guess case insensitiveness would be sweet, but I'm not a fan of PowerShell's capitalization (I'm a snake_case kind of guy). However, if it's a feature wanted by many people, I'll comply ;)

Cheers,

Y

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
I think we can close this issue now :laughing: 
However, feel free to open a pull request.

:sunflower:
