### ISSUE TITLE
Kali 2020 compatibility

### ISSUE THREAD

**Issue by Chantal2019** [the-useless-one/pywerview#38]
it does not work with either python 2.7 or 3 in new kali 

raceback (most recent call last):
  File "pywerview.py", line 21, in <module>
    from pywerview.cli.main import main
  File "/root/HADES/pywerview-fix_preauth/pywerview/cli/main.py", line 22, in <module>
    from pywerview.cli.helpers import *
  File "/root/HADES/pywerview-fix_preauth/pywerview/cli/helpers.py", line 21, in <module>
    from pywerview.functions.net import NetRequester
  File "/root/HADES/pywerview-fix_preauth/pywerview/functions/net.py", line 22, in <module>
    from impacket.dcerpc.v5.ndr import NULL
ImportError: No module named impacket.dcerpc.v5.ndr

**Comment by Chantal2019** [comment]
and python3 
Traceback (most recent call last):
  File "pywerview.py", line 21, in <module>
    from pywerview.cli.main import main
  File "/root/HADES/pywerview-fix_preauth/pywerview/cli/main.py", line 467
    print x
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(x)?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi,
On your first post, impacket (python 2 version) seems not be installed on your machine. On your second post, you try to execute a python 2 script with python 3, hence the error.

:sunflower:

**Comment by the-useless-one** [comment]
Hi @Chantal2019,

We're in the middle of porting pywerview to Python 3 (see the PR [here](https://github.com/the-useless-one/pywerview/pull/34)), but there are still some bugs we need to iron out (see the PR [here](https://github.com/SecureAuthCorp/impacket/pull/832)).

Thanks for your patience while we try to fix this stuff!

Cheers,

Y

**Comment by Chantal2019** [comment]
Thank you so much guys ::)

**Comment by the-useless-one** [comment]
Hi @Chantal2019,

`pywerview` is now Python 3 compatible and works in Kali 2022. Closing.
