### ISSUE TITLE
pycrypto module requirement

### ISSUE THREAD

**Issue by Qazeer** [the-useless-one/pywerview#44]
Hello!

Is the `pycrypto` module still required (as specified in the `install_requires`)?

The `pycrypto` project is no longer maintained and causes issues for standalone build on Windows (due to incompatibility with recent VS build tools).

I haven't seen any usage of `pycrypto` in the code after a quick glance and it is no longer required by `impacket` ([#485](https://github.com/SecureAuthCorp/impacket/pull/485)). I removed the requirements and could successfully setup `pywerview` as well as call a few submodules.

If `pycrypto` is required, would it be possible to replace it by `pycryptodome` (a good transparent replacement with the same namespace / functions)?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
Yes you are right, I think we need to clean up the `setup.py` file to match `requirements.txt`. I'll try to fix (and test!) this soon.

:sunflower:

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hey!

As you probably saw, I pushed a fix for this issue in `develop`. I'm not familiar with dependency management but I think it's ok now.

:sunflower:

**Comment by Qazeer** [comment]
Hi!

Thank you 👍

**Comment by mpgn** [comment]
Hello @ThePirateWhoSmellsOfSunflowers 

Can you also push it to master and push it to pip ? This is a blocking point for us to generate the docker image.

Thanks :)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Salut 😄 !

I'm currently away from keyboard but I'll take a look.

🌻

**Comment by the-useless-one** [comment]
Hi all! We're back from vacation and we were able to push the new release to PyPI. Hope this helps!

**Comment by maaaaz** [comment]
In case crypto functions are still needed, use `pycryptodome` instead of `pycrypto`.
