### ISSUE TITLE
get-objectacl

### ISSUE THREAD

**Issue by s0i37** [the-useless-one/pywerview#45]
Hello.
Very cool!!!
But thats about ACL audit with `get-objectacl`?
Nowadays viewing ACL from under Linux is not very comfortable...

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,

Sorry for the (extremely) late response. ACL auditing is really hard to implement and we don't think that the goal of pywerview (used as a tool) is to perform "heavy" computing on the returned results. Complex handling must be implemented in a separate script with pywerview used as a library. However, as pywerview can return json results, you can use powerful (but not so friendly :disappointed: ) tools such as `jq`.

Feel free to submit a PR if you manage to implement it.

:sunflower:
