### ISSUE TITLE
get-netloggedon does not work properly on Windows XP

### ISSUE THREAD

**Issue by ThePirateWhoSmellsOfSunflowers** [the-useless-one/pywerview#6]
I have this exception when I try to use `get-netloggedon` against XP box (yeah, I know, deprecated, but...).
Seems more an impacket error but maybe you could PR the project :D or tag this issue as "won't fix" :(
(tested with "git clone" version of impacket, not the stable release) 
### PywerView

`$ ./pywerview.py get-netloggedon -w DOMAIN.lan -u administrator -p p@ssw0rd --computername WINDOWSXP.domain.lan`

> Traceback (most recent call last):
>   File "./pywerview.py", line 279, in <module>
>     results = args.func(**parsed_args)
>   File "/home/x/tools/pywerview/pywerview/net.py", line 467, in get_netloggedon
>     resp = wkst.hNetrWkstaUserEnum(dce, 1)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/wkst.py", line 1020, in hNetrWkstaUserEnum
>     return dce.request(request)
>   File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 837, in request
>     answer = self.recv()
>   File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 1299, in recv
>     raise DCERPCException(rpc_status_codes[status_code])
> impacket.dcerpc.v5.rpcrt.DCERPCException: rpc_x_bad_stub_data
### Powerview

`PS C:\Users\administrator> Get-NetLoggedon -ComputerName WINDOWSXP.domain.lan`

> wkui1_username                wkui1_logon_domain            wkui1_oth_domains             wkui1_logon_server
> ---
> 
> WINDOWSXP$                    DOMAIN
> j.doe                         DOMAIN                                                      DC-DOMAIN

Thanks, very usefull tool :+1: 

"The old polish man still uses XP"

**Comment by the-useless-one** [comment]
Hmm, I'll have to look more procisely, but it indeed looks like a problem in impacket. I'll try to see if I can identify the problem/PR, or open an issue in impacket's repo, or simply drop support for Win XP, but the latter would be a shame :disappointed:.

I'll keep you posted, thanks!

**Comment by asolino** [comment]
Hey folks 

Can you specify the XP version?.. I just tested it against an XP SP3 and there's no error

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi Alberto,
I'm not sure but I think it was Windows XP Pro SP3 (French edition)

**Comment by asolino** [comment]
Just tested against a XP SP0 English:

```
./pywerview.py get-netloggedon -w DOMAIN.lan -u administrator -p admin --computername 172.16.123.187
wkui1_logon_domain: WORKGROUP
wkui1_logon_server: 
wkui1_oth_domains:  
wkui1_username:     WIN-XP-SP0$

wkui1_logon_domain: WIN-XP-SP0
wkui1_logon_server: WIN-XP-SP0
wkui1_oth_domains:  
wkui1_username:     beto
```

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Bump,

Other mission, somewhere else :

### Powerview (with mimikatz pth)

```
PS C:\Windows\system32> Get-NetLoggedon -ComputerName windowsxp.my.domain

wkui1_username      wkui1_logon_domain  wkui1_oth_domains   wkui1_logon_server
--------------      ------------------  -----------------   ------------------
COMPUTER$           WORLD
JOHNDOE             WORLD                                   DC00
```

### Pywerview (dev branch)

```
$ ./pywerview.py get-netloggedon -w world.my.domain -u Joe -p P@$$w0rd --computername windowsxp.my.domain
Traceback (most recent call last):
  File "./pywerview.py", line 24, in <module>
    main()
  File "/home/xxx/tools/pywerview-develop/pywerview/cli/main.py", line 419, in main
    results = args.func(**parsed_args)
  File "/home/xxx/tools/pywerview-develop/pywerview/cli/helpers.py", line 158, in get_netloggedon
    return requester.get_netloggedon()
  File "/home/xxx/tools/pywerview-develop/pywerview/requester.py", line 212, in wrapper
    instance._create_rpc_connection(pipe=pipe)
  File "/home/xxx/tools/pywerview-develop/pywerview/requester.py", line 198, in _create_rpc_connection
    wmi.IID_IWbemLevel1Login)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1056, in CoCreateInstanceEx
    iInterface = scm.RemoteCreateInstance(clsid, iid)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1837, in RemoteCreateInstance
    resp = self.__portmap.request(request)
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 858, in request
    raise exception
impacket.dcerpc.v5.dcomrt.DCERPCSessionError: DCOM SessionError: unknown error code: 0x800706ba
```

### Pywerview (stable)

```
$ ./pywerview.py get-netloggedon -w world.my.domain -u Joe -p P@$$w0rd --computername windowsxp.my.domain
$
```

Some information about the target :

```
$ ./pywerview.py get-netcomputer -w world.my.domain --dc-ip 10.0.0.1 -u Joe -p P@$$w0rd --computername windowsxp.my.domain --full-data
[...]
operatingsystem:            Windows XP Professional
operatingsystemservicepack: Service Pack 3
operatingsystemversion:     5.1 (2600)
[...]
```

Cheers dude :palm_tree:

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Closing, I have never retested pywerview against XP since this issue.
