### ISSUE TITLE
get-adserviceaccount command doesn't exist (get-netgmsa is what enumerates gMSA accounts)

### ISSUE THREAD

**Issue by keyos1** [the-useless-one/pywerview#62]
Hi,
in the latest README.md the gMSA enumeration command is marked as get-adserviceaccount.
However the code uses get-netgmsa instead.

Could you please fix it to be aligned with the documentation ?

Thank you

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!

Good catch, it is now fixed, thanks.

:sunflower:
