### ISSUE TITLE
Dependency documentation broken

### ISSUE THREAD

**Issue by jsherwood0** [the-useless-one/pywerview#68]
I'd like to apologize in advance if this issue comes off as pedantic or nitpicky. I'm not trying to cause problems, just help avoid them.

### Replication Environment ###

python version: 3.12.7
pywerview version: Commit: cbb0e7e51a3bb5eff650aace561beddac010250e
pipx version: 1.7.1

### Observed Results ###

When installing `pywerview` using `pipx`, the reported dependencies (from `requirements.txt`) fail to result in the proper installation of impacket (possibly due to the specific version specified in the `requirements.txt` file) and bs4 (possibly because `bs4` is listed as `beautifulsoup4` in the `requirements.txt`), causing execution of `pywerview` to fail:

```
ModuleNotFoundError: No module named 'impacket'
```

Then once you inject the current version of impacket from github:

```
ModuleNotFoundError: No module named 'bs4'
```

Once you have `pipx` inject both `bs4` and the version of impacket currently present on github into the venv for `pywerview` using the following commands, the script works:

```bash
pipx inject pywerview git+https://github.com/fortra/impacket.git
pipx inject pywerview bs4
```

### Expected Results ###

The project uses either `pyproject.toml` or `requirements.txt` to accurately specify the dependencies of the project while avoiding requirements for specific versions wherever possible. When specific versions are required, the functionality of your project is dependent on the version listed a) being present and b) not conflicting with versions required by other projects. If the project relies on features introduced in a specific version of the dependency, then the version requirements should be specified in the broadest possible syntax. That is, avoid very restrictive syntaxes such as:

* `==0.5`, which fails if v0.5 cannot be used for any reason
* `^1` or `~1`, which fails if v2.x is required on the system for any reason
* `^0.5`, which fails if v0.6 or higher is required on the system for any reason
* `~1.2` or `~1.2.3`, which both fail if v1.3 or higher is required on the system for any reason
* `@db71504529008bdbdd900549f6e4293be2e32c88`, which fails if ***any*** other version of the dependency is required for any reason.

**Note:** I understand that these syntaxes exist for a reason and that they have a valid use. The problem comes when they are not updated and projects stop working when simply using the current version of a dependency fixes the problem. Basically, minimizing their use minimizes the additional management overhead of tracking which dependencies need to be updated when other projects make changes.

**Comment by fabaff** [comment]
Could be related to the removal of the  `install_requires` section with 753074dfb9e822be85c79164d1a52f1058f934b9.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
I'm not very familiar with packaging tools (neither with pipx). Is it better if I put dependencies back into setup.py ?
Thanks

🌻

**Comment by jsherwood0** [comment]
> Hi! I'm not very familiar with packaging tools (neither with pipx). Is it better if I put dependencies back into setup.py ? Thanks
> 
> 🌻

I think that the easiest way (and the trending way as far as I can tell) to include dependencies is to use a `pyproject.toml` file. Basically it documents the requirements of the project (and a bunch of other stuff) and can be used for any build system (e.g., setuptools, poetry, etc.), and keeps the dependencies in one place so you don't have to make updates to both `requirements.txt` and `setup.py`. That said, I'm far from an expert, but I think that this page should give a decent overview:

https://packaging.python.org/en/latest/specifications/pyproject-toml/

**Comment by jsherwood0** [comment]
And this page provides a tutorial as to the current preferred method of structuring a python project so that it works with all distribution methods (e.g., pip, pipenv, pipx, poetry, etc.):

https://packaging.python.org/en/latest/tutorials/packaging-projects/

I hope all of this is helpful! Thanks for being responsive! =)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello!

Can you try this one ?

https://github.com/the-useless-one/pywerview/tree/pyproject

:sunflower:

**Comment by jsherwood0** [comment]
Hello. It looks like there might be a problem with the branch since it says that there is no module named 'pywerview'. In the screenshot below I've shown the results with both the new branch and the master branch. For your convenience, you can test whether the project installs correctly by using the following command:

```bash
# Usage is:
#  pipx install git+https://github.com/the-useless-one/pywerview@${BRANCHNAMEORHASH}

# To see it working on the previous build and verify how it should work:
> pipx install git+https://github.com/the-useless-one/pywerview@cbb0e7e
⚠️   Note: pywerview was already on your PATH at /usr/local/bin/pywerview
  installed package pywerview 0.7.2, installed using Python 3.12.6
  These apps are now globally available
    - pywerview
done! ✨ 🌟 ✨

> pywerview
usage: pywerview [-h]
                 {get-adobject,get-objectowner,get-netgmsa,get-netsmsa,get-objectacl,get-netuser,get-netgroup,get-netcomputer,get-netdomaincontroller,get-netfileserver,get-dfsshare,get-netou,get-netsite,get-netsubnet,get-netdomaintrust,get-netgpo,get-netpso,get-domainpolicy,get-gpttmpl,get-netgpogroup,find-gpocomputeradmin,find-gpolocation,get-netgroupmember,get-netsession,get-localdisks,get-netdomain,get-netshare,get-netloggedon,get-netlocalgroup,invoke-checklocaladminaccess,get-netprocess,get-userevent,invoke-userhunter,invoke-processhunter,invoke-eventhunter}
                 ...
pywerview: error: the following arguments are required: submodule

# To remove the old build and try the new branch:
> pipx uninstall pywerview
uninstalled pywerview! ✨ 🌟 ✨

> pipx install git+https://github.com/the-useless-one/pywerview@pyproject
⚠️   Note: pywerview was already on your PATH at /usr/local/bin/pywerview
  installed package pywerview 0.7.2, installed using Python 3.12.6
  These apps are now globally available
    - pywerview
done! ✨ 🌟 ✨

> pywerview
Traceback (most recent call last):
  File "/root/.local/bin/pywerview", line 5, in <module>
    from pywerview.cli.main import main
ModuleNotFoundError: No module named 'pywerview'
```
You'll also want to make sure that `~/.local/bin` is at the front of the path so that the pipx virtual environment executables are called before any others on your path. If that is the case, then any python packages on the rest of your system should not matter, though you _may_ want to remove pywerview and its dependencies from your main python packages just to be sure that no strange interaction occurs.

I hope this helps!

-John

Here it is failing on the new branch and on the master branch:

![image](https://github.com/user-attachments/assets/f5a46982-3b6b-4a9c-a3a1-dcc220cd3376)

And here it is succeeding on v0.7.0 (Commit: [cbb0e7e](https://github.com/the-useless-one/pywerview/commit/cbb0e7e51a3bb5eff650aace561beddac010250e)):

![image](https://github.com/user-attachments/assets/9cfa4574-1460-4add-aa65-c6f3f8c884b6)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Ok, I messed up, but i think now is good (fingers crossed)

```bash
user@goad:~/pywerview (pyproject) $ pipx install .
  installed package pywerview 0.7.2, installed using Python 3.10.12
  These apps are now globally available
    - pywerview
done! ✨ 🌟 ✨
user@goad:~/pywerview (pyproject) $ pywerview -h
usage: pywerview [-h]
                 {get-adobject,get-objectowner,get-netpki,get-netcerttmpl,get-netgmsa,get-netsmsa,get-objectacl,get-netuser,get-netgroup,get-netcomputer,get-netdomaincontroller,get-netfileserver,get-dfsshare,get-netou,get-netsite,get-netsubnet,get-netdomaintrust,get-netgpo,get-netpso,get-domainpolicy,get-gpttmpl,get-netgpogroup,find-gpocomputeradmin,find-gpolocation,get-netgroupmember,get-netsession,get-localdisks,get-netdomain,get-netshare,get-netloggedon,get-netlocalgroup,invoke-checklocaladminaccess,get-netprocess,get-userevent,invoke-userhunter,invoke-processhunter,invoke-eventhunter}
                 ...

Rewriting of some PowerView's functionalities in Python

options:
[...]
```

Can you retry please? I have rebased the branch

:sunflower:

**Comment by ShutdownRepo** [comment]
Seems alright ✅
<img width="1293" alt="image" src="https://github.com/user-attachments/assets/1f59427a-1de1-4949-9839-62b1b75ada1b" />

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
pypi seems not happy with my dependency definition of impacket :sob: 

```bash
$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your API token: 
Uploading pywerview-0.7.2-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB • 00:00 • 1.2 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.               
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                      
         Can't have direct dependency: impacket@                                              
         git+https://github.com/fortra/impacket@master. See                                   
         https://packaging.python.org/specifications/core-metadata for more information. 
 ```

The answer is: "Pypi and other standards-conformant package indices do not accept packages that declare dependencies using direct URLs. pip will accept them when installing packages from the local filesystem or from another URL, however." [source](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html)

We need to find a solution in order to publish pywerview on pypi, however I think it is another issue.
I'm closing this one, feel free to re-open it if needed.

Thanks all for the help.

:sunflower:
