### ISSUE TITLE
Set a default query if arguments are missing in get-adobject

### ISSUE THREAD

**Issue by ThePirateWhoSmellsOfSunflowers** [the-useless-one/pywerview#7]
Hi dude !

When `get-adobject` is used without argument an exception occurs. Maybe you could specify the mandatory arguments in the README or you could set a default query filter such as in Powerview (a wildcard).
### PywerView

`$ ./pywerview.py get-adobject -w DOMAIN.lan -u administrator -p p@ssw0rd --dc-ip 192.168.1.1`

> Traceback (most recent call last):
>   File "./pywerview.py", line 279, in <module>
>     results = args.func(**parsed_args)
>   File "/home/x/tools/pywerview/pywerview/net.py", line 46, in get_adobject
>     raise ValueError('[!] Must give at least one argument in '\
> ValueError: [!] Must give at least one argument in (queried_sid, queried_name, queried_sam_account_name)
### Powerview

`PS C:\Users\administrator> Get-ADObject`

> msds-isdomainfor                 : CN=NTDS Settings,CN=DC-DOMAIN,CN=Servers,CN=Default-First-Site-Name,CN=Sites,CN=Configuration,DC=domain,DC=lan
> lockoutobservationwindow         : -18000000000
> iscriticalsystemobject           : True
> maxpwdage                        : -36288000000000
> [...]

:+1:

"But there is no fly"

**Comment by the-useless-one** [comment]
Hi man,

I misinterpreted the default behaviour of PowerView's `Get-ADObject`. I thought it failed, but instead, it returns every AD Object.

I fixed the default behavior of PywerView's `get-adobject`: if no argument is given, it will return every AD object from the DC. Hope this is satisfactory!

Cheers,

Yannick
