### ISSUE TITLE
get-netgroupmember does not diplay login

### ISSUE THREAD

**Issue by ThePirateWhoSmellsOfSunflowers** [the-useless-one/pywerview#8]
Not really an issue, but `get-netgroupmember` does not diplay the Windows's login on its output. In Powerview, `MemberName` is the account's login and in PywerView it's just the full name. Moreover `groupdomain` value are not the same in this example and I don't know why (maybe this is another issue).
### PywerView

`$ ./pywerview.py get-netgroupmember -w DOMAIN.lan -u administrator -p p@ssw0rd --dc-ip 192.168.1.1 --groupname Compta`

> groupdomain:  None
> groupname:    Compta
> isgroup:      False
> memberdn:     CN=Jane Doe,OU=gq,DC=domain,DC=lan
> memberdomain: domain.lan
> membername:   Jane Doe
### Powerview

`PS C:\Users\administrator> Get-NetGroupMember -Groupname Compta`

> GroupDomain  : domain.lan
> GroupName    : Compta
> MemberDomain : domain.lan
> MemberName   : j.doe
> MemberSid    : S-X-X-XX-XXXXXXXXXX-XXXXXXXXXX-XXXXXXXXXX-XXXX
> IsGroup      : False
> MemberDN     : CN=Jane Doe,OU=gq,DC=domain,DC=lan

And bla bla thanks bla bla nice tool bla bla :thumbs up:

"quote"

**Comment by the-useless-one** [comment]
Greetings, pentest artisan.

I did not use the correct attribute in the result of get-netgroupmember, indeed. I used the common name instead of the sAMAccountName. Should be fixed now.

I also added the member's SID (which I had forgotten to add), and the way the "GroupDomain" attribute is processed.

Cheers,

Yannick

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Ahhh you da real MVP man !
Just a question, what's the difference between `memberdomain` and `groupdomain` attributes ?

**Comment by the-useless-one** [comment]
You can have a user `user_A` in a domain `domain_A`, who is a member of group `group_B` in domain `domain_B`. In that case, `memberdomain=domain_A` and `groupdomain=domain_B`.

However, I've still not tested PywerView against domains with foreign users. Should be done soon ;)
